"""
Glucose Prediction from Filtered Windows CSV

This script reads filtered PPG windows from a CSV file (generated by the web app)
and predicts glucose values using the ResNet34-1D model.

Usage:
    python glucose_from_csv.py <path_to_filtered_windows_detailed.csv>

Example:
    python glucose_from_csv.py web_app_data/case_2_SNUADC_PLETH/case_2_SNUADC_PLETH_raw_cleansed_filtered_windows_detailed.csv
"""

import sys
import os
import pandas as pd
import numpy as np
from src.training.resnet34_glucose_predictor import GlucosePredictor


def load_windows_from_csv(csv_file):
    """
    Load filtered windows from CSV file.

    The CSV has format:
        window_index, sample_index, amplitude
        0, 0, -9.4853
        0, 1, -9.5275
        ...

    Parameters:
    -----------
    csv_file : str
        Path to filtered_windows_detailed.csv

    Returns:
    --------
    windows : List[np.ndarray]
        List of PPG signal windows
    """
    print(f"Loading windows from: {csv_file}")

    # Read CSV
    df = pd.read_csv(csv_file)

    # Group by window_index
    windows = []
    for window_idx in sorted(df['window_index'].unique()):
        # Get all samples for this window
        window_df = df[df['window_index'] == window_idx].sort_values('sample_index')
        window = window_df['amplitude'].values
        windows.append(window)

    print(f"Loaded {len(windows)} windows")
    if len(windows) > 0:
        print(f"Window length: {len(windows[0])} samples")

    return windows


def predict_glucose_from_csv(csv_file, output_dir=None):
    """
    Predict glucose from filtered windows CSV file.

    Parameters:
    -----------
    csv_file : str
        Path to filtered_windows_detailed.csv
    output_dir : str, optional
        Directory to save results (default: same as input CSV)
    """
    print("=" * 80)
    print("Glucose Prediction from Filtered Windows CSV")
    print("=" * 80)

    # =========================================================================
    # STEP 1: Load Filtered Windows from CSV
    # =========================================================================
    print("\n[STEP 1] Loading filtered windows from CSV...")

    if not os.path.exists(csv_file):
        print(f"[ERROR] File not found: {csv_file}")
        return

    try:
        windows = load_windows_from_csv(csv_file)
    except Exception as e:
        print(f"[ERROR] Failed to load windows: {e}")
        return

    if len(windows) == 0:
        print("[ERROR] No windows found in CSV file")
        return

    print(f"[SUCCESS] Loaded {len(windows)} windows")
    print(f"   Window length: {len(windows[0])} samples")

    # =========================================================================
    # STEP 2: Initialize Glucose Predictor
    # =========================================================================
    print("\n[STEP 2] Initializing ResNet34-1D glucose predictor...")

    window_length = len(windows[0])
    predictor = GlucosePredictor(
        input_length=window_length,
        device='cpu'  # Use 'cuda' if GPU available
    )

    print(predictor.get_model_summary())

    # =========================================================================
    # STEP 3: Predict Glucose Values
    # =========================================================================
    print(f"\n[STEP 3] Running inference on {len(windows)} windows...")

    try:
        glucose_results = predictor.predict_with_stats(windows, batch_size=32)
    except Exception as e:
        print(f"[ERROR] Prediction failed: {e}")
        import traceback
        traceback.print_exc()
        return

    # =========================================================================
    # STEP 4: Display Results
    # =========================================================================
    print("\n" + "=" * 80)
    print("GLUCOSE PREDICTION RESULTS")
    print("=" * 80)

    print(f"\nGlucose Statistics:")
    print(f"   Mean Glucose:  {glucose_results['mean_glucose']:.2f} mg/dL")
    print(f"   Std Deviation: {glucose_results['std_glucose']:.2f} mg/dL")
    print(f"   Min Glucose:   {glucose_results['min_glucose']:.2f} mg/dL")
    print(f"   Max Glucose:   {glucose_results['max_glucose']:.2f} mg/dL")
    print(f"   Num Windows:   {glucose_results['num_windows']}")

    # Show first 10 predictions
    predictions = glucose_results['predictions']
    print(f"\nFirst 10 Glucose Predictions:")
    print(f"{'Window':<10} {'Glucose (mg/dL)':<20}")
    print("-" * 30)
    for i in range(min(10, len(predictions))):
        print(f"{i:<10} {predictions[i]:<20.2f}")

    # =========================================================================
    # STEP 5: Save Results
    # =========================================================================
    print(f"\n[STEP 5] Saving results...")

    # Determine output directory
    if output_dir is None:
        output_dir = os.path.dirname(csv_file)

    # Create output filename
    base_name = os.path.basename(csv_file)
    base_name = base_name.replace('_filtered_windows_detailed.csv', '')
    output_file = os.path.join(output_dir, f'{base_name}_glucose_predictions.csv')

    # Save glucose predictions to CSV
    glucose_df = pd.DataFrame({
        'window_index': range(len(predictions)),
        'glucose_mg_dl': predictions
    })

    glucose_df.to_csv(output_file, index=False)

    print(f"[SUCCESS] Glucose predictions saved to: {output_file}")

    # =========================================================================
    # NOTES
    # =========================================================================
    print("\n" + "=" * 80)
    print("IMPORTANT NOTES:")
    print("=" * 80)
    print("""
1. The model used here is UNTRAINED. Predictions are random.

2. To use in production:
   - Train the ResNet34 model on labeled PPG-glucose paired data
   - Save the trained model: predictor.save_model('glucose_model.pth')
   - Load for inference: predictor = GlucosePredictor(model_path='glucose_model.pth')

3. Training requirements:
   - Paired dataset: PPG windows + corresponding glucose measurements
   - Typical dataset size: 10,000+ samples
   - Training time: Several hours on GPU

4. Model performance metrics:
   - MAE (Mean Absolute Error): Typical target < 15 mg/dL
   - RMSE (Root Mean Squared Error): Typical target < 20 mg/dL

5. Clinical validation required before medical use.
""")

    print("=" * 80)
    print("[SUCCESS] Processing completed successfully!")
    print("=" * 80)


def main():
    """Main entry point."""
    # Check command line arguments
    if len(sys.argv) < 2:
        print("Usage: python glucose_from_csv.py <path_to_filtered_windows_detailed.csv>")
        print("\nExample:")
        print("  python glucose_from_csv.py web_app_data/case_2_SNUADC_PLETH/case_2_SNUADC_PLETH_raw_cleansed_filtered_windows_detailed.csv")
        print("\nAvailable CSV files:")

        # Try to find CSV files
        if os.path.exists('web_app_data'):
            import glob
            csv_files = glob.glob('web_app_data/**/*filtered_windows_detailed.csv', recursive=True)
            if csv_files:
                for i, f in enumerate(csv_files[:5], 1):
                    print(f"  {i}. {f}")
            else:
                print("  No filtered windows CSV files found in web_app_data/")
        else:
            print("  web_app_data/ directory not found")

        sys.exit(1)

    csv_file = sys.argv[1]

    # Optional: output directory
    output_dir = sys.argv[2] if len(sys.argv) > 2 else None

    # Run prediction
    predict_glucose_from_csv(csv_file, output_dir)


if __name__ == '__main__':
    main()
